# Generated by Django 4.0.4 on 2022-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
    ]
